In [11]:
from modules.data_cleaning import *
from modules.fuzz_flow import *
from modules.params import path_to_data
import pandas as pd
from datetime import datetime

In [22]:
df = fuzz_flow()

df.to_csv('/Users/alexhergert/code/Xander78261/ticket-control-bvg/datadf.cvs')

sample_df = df.sample(n=100, random_state=42)

Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '̈']
/Users/alexhergert/code/Xander78261/ticket-control-bvg/modules/fuzz_flow.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_chat["station_key"] = data3["text"].map(station_finder)

In [53]:
sample_df

,station_key,text,station name,lines,area,latitude,longitude
date,,,,,,,
2022-12-08 11:24:34,gesundbrunnen,kontrolle u8 gleich gesundbrunnen,Gesundbrunnen,"U8, S1, S2, S25, S26, S41, S42",Gesundbrunnen,52.548611,13.381250
2023-02-15 09:57:29,tempelhof,ringbahn s41 tempelhof blue jackets sorry bl...,Tempelhof,"U6, S41, S42, S45, S46",Tempelhof,52.470833,13.385278
2019-05-28 14:25:02,greifswalder str,s41 greifswalder str junger typ kappe brille,Greifswalder Straße,"S41, S42, S8, S85",PrenzlauerBerg,52.540000,13.440556
2023-06-07 10:13:14,voltastr,u8 voltastr blauwesten bos sicherheitsdienste,Voltastraße,U8,Gesundbrunnen,52.542222,13.393056
2022-04-27 08:45:18,tempelhof,s41 tempelhof 3 1 kurze,Tempelhof,"U6, S41, S42, S45, S46",Tempelhof,52.470833,13.385278
...,...,...,...,...,...,...,...
2022-04-18 14:35:24,westend,m6 oderbruchstr ri hbf blauwesten ner gruppe,Westend,"S41, S42, S46",Charlottenburg,52.518056,13.284444
2019-01-07 12:37:56,klosterstr,klosterstr bahnsteig,Klosterstraße,U2,Mitte,52.516111,13.412222
2020-08-26 16:04:06,bellevue,s9 hbf 4 kontrolleure,Bellevue,"S3, S5, S7, S9",Hansaviertel,52.520000,13.347778
2021-08-11 11:45:49,nollendorfplatz,etwa 4 kontrollettis lungern u bahnhof nollend...,Nollendorfplatz,"U1, U3, U4, U1, U3, U2",Schöneberg,52.499444,13.353611
2021-11-11 14:09:57,koepenick,2 kontros m tram 62 nach wendenschloss gerad...,Köpenick,S3,Köpenick,52.458611,13.580833

In [54]:
df.reset_index(inplace=True)
df

,index,date,station_key,text,station name,lines,area,latitude,longitude
0,0,2018-02-15 12:03:54,wildau,https shopdigitalcouragedelichtbildausweismit...,Wildau,S46,Wildau,52.320000,13.633889
1,1,2018-02-15 18:44:50,erkner,kritik durchaus berechtigt sehe aba tatsache g...,Erkner,S3,Erkner,52.429722,13.751389
2,2,2018-02-16 07:39:11,hellersdorf,hoelle,Hellersdorf,U5,Hellersdorf,52.536667,13.606389
3,3,2018-02-16 12:12:04,zoo,s3s5s7s9 berlin hbf kontrolleure weitergefah...,Zoologischer Garten,"U2, U9, S3, S5, S7, S9",Charlottenburg,52.507222,13.332500
4,4,2018-02-16 14:31:21,beusselstr,beusselstr s42 glaube beussel,Beusselstraße,"S41, S42",Moabit,52.534444,13.329444
...,...,...,...,...,...,...,...,...,...
60337,60337,2023-08-18 11:16:15,hermannplatz,u7 hermannplatz richtung spandau 2 kontrolleur...,Hermannplatz,"U7, U8",Neukölln,52.487222,13.424722
60338,60338,2023-08-18 11:28:34,treptower park,s42 ringbahn treptower park 3 personen,Treptower Park,"S41, S42, S8, S85, S9",Alt-Treptow,52.493889,13.461389
60339,60339,2023-08-18 11:33:54,beusselstr,beusselstr rotes balenciaga,Beusselstraße,"S41, S42",Moabit,52.534444,13.329444
60340,60340,2023-08-18 12:10:31,friedrichsfelde,u5 friedrichsfelde 2x blau,Friedrichsfelde,U5,Friedrichsfelde,52.506111,13.512778
60341,60341,2023-08-18 12:36:47,mehringdamm,u6 mehringdamm station,Mehringdamm,"U6, U7",Kreuzberg,52.494444,13.388611

In [68]:
comparison_date = datetime(2023, 8, 13, 12, 3, 54)

filtered_df = df[df['date'] > comparison_date]

In [69]:
filtered_df

,index,date,station_key,text,station name,lines,area,latitude,longitude
60160,60160,2023-08-13 12:16:27,alex,s 7539 around alex m coded black t shirts no...,Alexanderplatz,"U2, U5, U8, S3, S5, S7, S9",Mitte,52.521389,13.412639
60161,60161,2023-08-13 12:23:04,schwartzkopffstr,u6 gerade schwarzkopf str stadtauswaerts,Schwartzkopffstraße,U6,Mitte,52.535278,13.377222
60162,60162,2023-08-13 13:25:06,hermannstr,kontrolle sbahn hermannstr weisse cap beige pe...,Hermannstraße,"U8, S41, S42, S45, S46, S47",Neukölln,52.467500,13.431250
60163,60163,2023-08-13 13:54:22,warschauer str,4 personen kontrolettiwesten warschauer str 2 ...,Warschauer Straße,"U1, U3, S3, S5, S7, S75, S9",Friedrichshain,52.505694,13.449722
60164,60164,2023-08-13 14:24:52,goerli,goerli bahnhof bos,Görlitzer Bahnhof,"U1, U3",Kreuzberg,52.499167,13.428056
...,...,...,...,...,...,...,...,...,...
60337,60337,2023-08-18 11:16:15,hermannplatz,u7 hermannplatz richtung spandau 2 kontrolleur...,Hermannplatz,"U7, U8",Neukölln,52.487222,13.424722
60338,60338,2023-08-18 11:28:34,treptower park,s42 ringbahn treptower park 3 personen,Treptower Park,"S41, S42, S8, S85, S9",Alt-Treptow,52.493889,13.461389
60339,60339,2023-08-18 11:33:54,beusselstr,beusselstr rotes balenciaga,Beusselstraße,"S41, S42",Moabit,52.534444,13.329444
60340,60340,2023-08-18 12:10:31,friedrichsfelde,u5 friedrichsfelde 2x blau,Friedrichsfelde,U5,Friedrichsfelde,52.506111,13.512778
60341,60341,2023-08-18 12:36:47,mehringdamm,u6 mehringdamm station,Mehringdamm,"U6, U7",Kreuzberg,52.494444,13.388611

In [121]:
stations_bh = pd.read_csv('datanew_map2.csv')

stations_bh

stations_bh = stations_bh[:-100]

stations_bh

,Unnamed: 0.1,Unnamed: 0,station name,lines,area,LAT,LON,Location,color
0,0,0.0,Adenauerplatz,U7,Charlottenburg,52.499722,13.307222,U7,#33B5FF
1,1,1.0,Adlershof,"S45, S46, S8, S85, S9",Adlershof,52.434722,13.541389,S and U Bahn,#FFC300
2,2,2.0,Afrikanische Straße,U6,Wedding,52.560556,13.334167,U6,#DA33FF
3,3,3.0,Ahrensfelde,S7,Marzahn,52.571667,13.565000,S7,#FF335D
4,4,4.0,Alexanderplatz,"U2, U5, U8, S3, S5, S7, S9",Mitte,52.521389,13.412639,S and U Bahn,#FFC300
...,...,...,...,...,...,...,...,...,...
313,313,313.0,Zepernick,S2,Panketal,52.659722,13.533889,S2,#00CC00
314,314,314.0,Zeuthen,S46,Zeuthen,52.348611,13.627500,S46,#FFA500
315,315,315.0,Zitadelle,U7,Haselhorst,52.537778,13.217778,U7,#33B5FF
316,316,316.0,Zoologischer Garten,"U2, U9, S3, S5, S7, S9",Charlottenburg,52.507222,13.332500,S and U Bahn,#FFC300
317,317,317.0,Zwickauer Damm,U7,Gropiusstadt,52.423333,13.483889,U7,#33B5FF

In [75]:
stations_bh
filtered_df

,index,date,station_key,text,station name,lines,area,latitude,longitude
60160,60160,2023-08-13 12:16:27,alex,s 7539 around alex m coded black t shirts no...,Alexanderplatz,"U2, U5, U8, S3, S5, S7, S9",Mitte,52.521389,13.412639
60161,60161,2023-08-13 12:23:04,schwartzkopffstr,u6 gerade schwarzkopf str stadtauswaerts,Schwartzkopffstraße,U6,Mitte,52.535278,13.377222
60162,60162,2023-08-13 13:25:06,hermannstr,kontrolle sbahn hermannstr weisse cap beige pe...,Hermannstraße,"U8, S41, S42, S45, S46, S47",Neukölln,52.467500,13.431250
60163,60163,2023-08-13 13:54:22,warschauer str,4 personen kontrolettiwesten warschauer str 2 ...,Warschauer Straße,"U1, U3, S3, S5, S7, S75, S9",Friedrichshain,52.505694,13.449722
60164,60164,2023-08-13 14:24:52,goerli,goerli bahnhof bos,Görlitzer Bahnhof,"U1, U3",Kreuzberg,52.499167,13.428056
...,...,...,...,...,...,...,...,...,...
60337,60337,2023-08-18 11:16:15,hermannplatz,u7 hermannplatz richtung spandau 2 kontrolleur...,Hermannplatz,"U7, U8",Neukölln,52.487222,13.424722
60338,60338,2023-08-18 11:28:34,treptower park,s42 ringbahn treptower park 3 personen,Treptower Park,"S41, S42, S8, S85, S9",Alt-Treptow,52.493889,13.461389
60339,60339,2023-08-18 11:33:54,beusselstr,beusselstr rotes balenciaga,Beusselstraße,"S41, S42",Moabit,52.534444,13.329444
60340,60340,2023-08-18 12:10:31,friedrichsfelde,u5 friedrichsfelde 2x blau,Friedrichsfelde,U5,Friedrichsfelde,52.506111,13.512778
60341,60341,2023-08-18 12:36:47,mehringdamm,u6 mehringdamm station,Mehringdamm,"U6, U7",Kreuzberg,52.494444,13.388611

In [87]:
stations_bh.to_csv("/Users/alexhergert/code/Xander78261/ticket-control-bvg/station_bahn1.csv")

In [118]:

def change_color(filtered_df, stations_bh):
    reports = filtered_df["station name"].unique()
    
    stations_bh["color"] = stations_bh["station name"].apply(lambda x: np.where(x in reports, "#FF0000", stations_bh["color"].loc[stations_bh["station name"]==x]))
    
    return stations_bh

In [ ]:
def change_color2(filtered_df, stations_bh):
    lambda x: x == "#FF0000" if filtered_df["station name"] == stations_bh["station name"]

In [122]:
change_color(filtered_df,stations_bh)

,Unnamed: 0.1,Unnamed: 0,station name,lines,area,LAT,LON,Location,color
0,0,0.0,Adenauerplatz,U7,Charlottenburg,52.499722,13.307222,U7,[#33B5FF]
1,1,1.0,Adlershof,"S45, S46, S8, S85, S9",Adlershof,52.434722,13.541389,S and U Bahn,[#FFC300]
2,2,2.0,Afrikanische Straße,U6,Wedding,52.560556,13.334167,U6,[#DA33FF]
3,3,3.0,Ahrensfelde,S7,Marzahn,52.571667,13.565000,S7,[#FF0000]
4,4,4.0,Alexanderplatz,"U2, U5, U8, S3, S5, S7, S9",Mitte,52.521389,13.412639,S and U Bahn,[#FF0000]
...,...,...,...,...,...,...,...,...,...
313,313,313.0,Zepernick,S2,Panketal,52.659722,13.533889,S2,[#00CC00]
314,314,314.0,Zeuthen,S46,Zeuthen,52.348611,13.627500,S46,[#FFA500]
315,315,315.0,Zitadelle,U7,Haselhorst,52.537778,13.217778,U7,[#33B5FF]
316,316,316.0,Zoologischer Garten,"U2, U9, S3, S5, S7, S9",Charlottenburg,52.507222,13.332500,S and U Bahn,[#FF0000]
317,317,317.0,Zwickauer Damm,U7,Gropiusstadt,52.423333,13.483889,U7,[#33B5FF]

In [123]:
stations_bh["color"][0]

array(['#33B5FF'], dtype=object)

In [52]:
stations_bh

,Unnamed: 0.1,Unnamed: 0,station name,lines,area,LAT,LON,Location,color
0,0,0.0,Adenauerplatz,U7,Charlottenburg,52.499722,13.307222,U7,#FF0000
1,1,1.0,Adlershof,"S45, S46, S8, S85, S9",Adlershof,52.434722,13.541389,S and U Bahn,#FF0000
2,2,2.0,Afrikanische Straße,U6,Wedding,52.560556,13.334167,U6,#FF0000
3,3,3.0,Ahrensfelde,S7,Marzahn,52.571667,13.565000,S7,#FF0000
4,4,4.0,Alexanderplatz,"U2, U5, U8, S3, S5, S7, S9",Mitte,52.521389,13.412639,S and U Bahn,#FF0000
...,...,...,...,...,...,...,...,...,...
313,313,313.0,Zepernick,S2,Panketal,52.659722,13.533889,S2,#FF0000
314,314,314.0,Zeuthen,S46,Zeuthen,52.348611,13.627500,S46,#FF0000
315,315,315.0,Zitadelle,U7,Haselhorst,52.537778,13.217778,U7,#FF0000
316,316,316.0,Zoologischer Garten,"U2, U9, S3, S5, S7, S9",Charlottenburg,52.507222,13.332500,S and U Bahn,#FF0000
317,317,317.0,Zwickauer Damm,U7,Gropiusstadt,52.423333,13.483889,U7,#FF0000